# Cleaning dataset with python

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"E:\pandas\Machine Learning\Projects\Car_details(U).csv")
data

,vehicle_uid,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,car_record_id,car_age,price_category,km_category,owner_count,fuel_transmission,brand,price_per_km,is_diesel
0,CAR_000001,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner,1,18,Low,NaN,0.0,Petrol_Manual,Maruti,0.86,0
1,CAR_000002,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,NaN,Individual,Manual,First Owner,2,18,Low,NaN,0.0,Petrol_Manual,Maruti,2.70,0
2,CAR_000003,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner,3,13,NaN,NaN,NaN,Diesel_Manual,Hyundai,6.00,1
3,CAR_000004,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner,4,8,Low,Medium,0.0,Petrol_Manual,Datsun,5.43,0
4,CAR_000005,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner,5,11,NaN,High,0.0,Diesel_Manual,Honda,3.19,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,CAR_004336,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999.0,NaN,Diesel,Individual,Manual,Second Owner,4336,11,Mid,High,0.0,Diesel_Manual,Hyundai,5.12,1
4336,CAR_004337,Hyundai i20 Magna 1.4 CRDi,2014,409999.0,80000.0,Diesel,Individual,NaN,Second Owner,4337,11,Mid,High,0.0,Diesel_Manual,Hyundai,5.12,1
4337,CAR_004338,Maruti 800 AC BSIII,2009,110000.0,83000.0,Petrol,Individual,Manual,Second Owner,4338,16,Low,High,NaN,Petrol_Manual,Maruti,1.33,0
4338,CAR_004339,Hyundai Creta 1.6 CRDi SX Option,2016,865000.0,NaN,Diesel,Individual,Manual,First Owner,4339,9,High,High,0.0,Diesel_Manual,Hyundai,9.61,1
4339,CAR_004340,Renault KWID RXT,2016,NaN,40000.0,Petrol,Individual,Manual,First Owner,4340,9,Low,Medium,0.0,Petrol_Manual,Renault,5.62,0

In [3]:
# 1. Identify the maximum and minimum values of the selling_price column.
#(Calculate the average of these two values and use this average tofill all missing values in selling_price.)

In [4]:
max_price = data["selling_price"].max()
min_price = data["selling_price"].min()

In [5]:
avg_value = (max_price+min_price)/2        # Average Calculation
avg_value

4461000.0

In [6]:
import warnings
warnings.filterwarnings("ignore")

In [7]:
#filling missing values
data["selling_price"].fillna(avg_value,inplace = True)

In [8]:
#2. Handle the km_driven and owner_count columns using an appropriate real-world data-cleaning technique.
#Justify the method used for each column based on data distributionand practical usage.

In [9]:
# filling KM missing value with median

In [10]:
data["km_driven"].fillna(data["km_driven"].median(),inplace= True)

In [11]:
# filling owner missing value with mode

In [34]:
data["owner_count"].fillna(data["owner_count"].mean(),inplace= True)

In [35]:
#3. For the km_category column, 50% of the missing values should be filled with the most frequently occurring category.
#The remaining 50% of missing values should be filled with the value "High".

In [36]:
data.head(2)

,vehicle_uid,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,car_record_id,car_age,price_category,km_category,owner_count,fuel_transmission,brand,price_per_km,is_diesel
0,CAR_000001,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner,1,18,Low,Medium,0.0,Petrol_Manual,Maruti,0.86,0
1,CAR_000002,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,Petrol,Individual,Manual,First Owner,2,18,Low,Medium,0.0,Petrol_Manual,Maruti,2.70,0

In [37]:
# Finding Mode

In [38]:
mode_km = data["km_category"].mode()[0]
mode_km

'Medium'

In [39]:
# Missing Index

In [40]:
missing_index = data[data["km_category"].isna()].index
missing_index

Index([], dtype='int64')

In [41]:
half = len(missing_index)//2
half

0

In [42]:
# first half

In [43]:
data.loc[missing_index[:half],"km_category"] = mode_km

In [44]:
# secong half

In [45]:
data.loc[missing_index[half:],"km_category"] = "High"

In [46]:
#4. Fill missing values in the price_category column using the most frequently occurring category in the dataset.
#If it is not possible to determine whether the category is generated manually or automatically, replace missing values with "Unknown".

In [47]:
if data["price_category"].mode().empty:
    data["price_category"].fillna("Unknown",inplace=True)
else:
    data["price_category"].fillna(data["price_category"].mode()[0],inplace=True)

In [48]:
#5. For the fuel column, distribute all missing values equally among the existing unique fuel types.
#Each unique fuel value must be assigned the same number of missing records.

In [49]:
fuel_type = data["fuel"].dropna().unique()
fuel_type

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [50]:
missing_index = data[data["fuel"].isna()].index
missing_index

Index([], dtype='int64')

In [51]:
n_types = len(fuel_type)
n_types

5

In [52]:
for i , idx in enumerate(missing_index):
    data.loc[idx,"fuel"] = fuel_type[i%n_types]

In [56]:
# filling Null values in Transmission Column (Extra Activity)

In [58]:
data["transmission"].fillna(data["transmission"].mode()[0],inplace=True)

In [59]:
# verify Cleaning

In [60]:
data.isnull().sum()

vehicle_uid          0
name                 0
year                 0
selling_price        0
km_driven            0
fuel                 0
seller_type          0
transmission         0
owner                0
car_record_id        0
car_age              0
price_category       0
km_category          0
owner_count          0
fuel_transmission    0
brand                0
price_per_km         0
is_diesel            0
dtype: int64

In [61]:
#6 – Split dataset into two CSV files

In [62]:
data.columns

Index(['vehicle_uid', 'name', 'year', 'selling_price', 'km_driven', 'fuel',
       'seller_type', 'transmission', 'owner', 'car_record_id', 'car_age',
       'price_category', 'km_category', 'owner_count', 'fuel_transmission',
       'brand', 'price_per_km', 'is_diesel'],
      dtype='object')

In [64]:
# File 1
vehicle_info = data[['vehicle_uid','name','year','fuel','seller_type',
                   'transmission','owner','brand','car_age']]
vehicle_info.to_csv(r"E:\pandas\Machine Learning\Projects\Mock Test data\vehicle_info.csv",index=False)

In [65]:
# File 2
vehicle_sales = data[['vehicle_uid','selling_price','km_driven',
                    'price_category','km_category']]

vehicle_sales.to_csv(r"E:\pandas\Machine Learning\Projects\Mock Test data\vehicle_sales.csv", index=False)